hm 2
dinamio/hillelee pull request #20
Opened 2018-04-12 16:06 UTC by romakonn1

2018-04-12 18:23 UTC, dinamio requested changes
Files from .idea doesn't need to be in pull request

2018-04-13 05:31 UTC, romakonn1 commented
removed .idea and target folders from git tracking

2018-04-13 07:47 UTC, dinamio requested changes

2018-04-13 07:47 UTC, dinamio commented on Kononov/testsort/testsort.iml
> +<?xml version="1.0" encoding="UTF-8"?>
This file is generated too, doesn't need to be in pr.

2018-04-13 07:47 UTC, dinamio commented on Kononov/testsort/src/main/java/Main.java
> +        QuickSort quickSort = new QuickSort();
Where is import for QuickSort?

2018-05-11 08:56 UTC, closed without merging