Kuznetsov home work#9
dinamio/hillelee pull request #47
Opened 2018-06-07 15:34 UTC by Muao

2018-06-08 11:41 UTC, dinamio requested changes
Please, change approach to controllers, and hibernate mapping

2018-06-08 11:41 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/controllers/LogOutController.java
> +        HttpServletResponse resp = (HttpServletResponse) servletResponse;
You are using controller as plain servlet. You can receive Session as parameter and return String with "redirect:/"

2018-06-08 11:41 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/controllers/LoginController.java
> +        RequestDispatcher loginDispatcher = req.getRequestDispatcher("/view/login.jsp");
The same here

2018-06-08 11:41 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/dao/impl/QuizDaoHibernate.java
> +        transaction.commit();
Get can work without transaction

2018-06-08 11:41 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/dao/impl/QuizDaoHibernate.java
> +public class QuizDaoHibernate implements QuizDao {
It's better to separate dao methods per entity.

2018-06-08 11:41 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/entities/QuestionsEntity.java
> +    @NaturalId
Bad idea twice
1. ThemeId is not natural id
2. In Hibernate Question must contain Theme, not only id

2018-06-08 11:41 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/entities/QuizzesEntity.java
> +@Component
Why you use component at entity?

2018-06-08 12:26 UTC, Muao commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/entities/QuizzesEntity.java
> +@Component
It left from the previous implementation

2018-06-12 11:02 UTC, dinamio approved these changes
Looks good

2018-06-12 11:02 UTC, dinamio commented on kuznetsov/quizzes/src/main/java/com/kuznetsov/controllers/QuizController.java
> +            req.setAttribute("list", services.getAllQuizzes());
This attribute idealogically must be in Model. But for now it's okay

2018-06-12 13:10 UTC, merged