Was added method sortBondarenko with realisation of quick list sorting
dinamio/hillelee pull request #5
Opened 2018-03-25 20:01 UTC by bondarenkodyu

2018-03-26 09:00 UTC, dinamio requested changes

2018-03-26 09:00 UTC, dinamio commented on SortLab/src/Main.java
> +//        List<Integer> list = IntStream.iterate(0, i -> new Random().nextInt()).limit(20).boxed().collect(toList());
You can uncomment this

2018-03-27 11:02 UTC, dinamio approved these changes
Looks good

2018-03-27 13:44 UTC, merged

2018-03-27 13:44 UTC, bondarenkodyu commented
Conflict was solved